name: MULTIPLE_REPO_SYNC

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */12 * * *

jobs:
  sync_repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { upstream: "OrekiYuta/Cink", target: "CatToCat/Cink", upstream_branch: "master", target_branch: "master" }
          - { upstream: "OrekiYuta/mermaid-presentation", target: "CatToCat/mermaid-presentation", upstream_branch: "main", target_branch: "main" }
          - { upstream: "OrekiYuta/Mont", target: "CatToCat/Mont", upstream_branch: "main", target_branch: "main" }
          - { upstream: "OrekiYuta/Hstiro", target: "CatToCat/Hstiro", upstream_branch: "main", target_branch: "main" }
          - { upstream: "OrekiYuta/orekiyuta.github.io", target: "CatToCat/orekiyuta.github.io", upstream_branch: "master", target_branch: "master" }

    steps:
      - name: Sync repo
        uses: CatToCat/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: ${{ matrix.repo.upstream }}
          target_repository: ${{ matrix.repo.target }}
          upstream_branch: ${{ matrix.repo.upstream_branch }}
          target_branch: ${{ matrix.repo.target_branch }}
          force: true
          tags: true
