name: SYNC_REPO_EVERYDAY

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */12 * * *

jobs:
  sync_repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { upstream: "OrekiYuta/orekiyuta.github.io", target: "CatToCat/orekiyuta.github.io" }
          - { upstream: "OrekiYuta/Mont", target: "CatToCat/Mont" }
          - { upstream: "OrekiYuta/Hstiro", target: "CatToCat/Hstiro"}
          - { upstream: "OrekiYuta/Cink", target: "CatToCat/Cink" }
    steps:
      - name: Sync repo
        uses: CatToCat/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: ${{ matrix.repo.upstream }}
          target_repository: ${{ matrix.repo.target }}
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
